### PR TITLE
UI Changes

### PR DESCRIPTION
**Pull request by junbug01**
Font changed to match with Avian Brand kit.
Site colors Updated to Avian Brand kit.
Footer Updated
image

### CODE REVIEW

**Review by alamshafil — APPROVED** [review]

**Comment by alamshafil** [comment]
Looks good code-wise, we can improve UI later. I will also fix the commits to contain your name.

**Comment by junbug01** [comment]
I merged it lol.

**Comment by alamshafil** [comment]
No problem, I already fixed it. All good to go!

**Comment by junbug01** [comment]
Thanks bro

**Pull request merged**
